# Generated by Django 5.2.15 on 2026-06-29 14:19

import apps.resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.CharField(db_index=True, default=apps.resume.models.generate_resume_id, max_length=20, unique=True)),
                ('user_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('profession', models.CharField(blank=True, default='', max_length=255)),
                ('resume_data', models.JSONField(default=dict)),
                ('ats_data', models.JSONField(blank=True, null=True)),
                ('qr_scan_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('pdf_download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Resume',
                'verbose_name_plural': 'Public Resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
