# Generated by Django 5.2.15 on 2026-07-01 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_qr_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resume',
            new_name='resume_resu_owner_i_bb2668_idx',
            old_name='resume_owner_created_idx',
        ),
        migrations.RenameIndex(
            model_name='resume',
            new_name='resume_resu_is_publ_887c4d_idx',
            old_name='resume_public_id_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeview',
            new_name='resume_resu_resume__c721f9_idx',
            old_name='resumeview_resume_at_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeview',
            new_name='resume_resu_visitor_0f320d_idx',
            old_name='resumeview_type_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='resume_skil_resume__3ac30f_idx',
            old_name='skill_resume_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='resume_skil_skill_n_f71c8f_idx',
            old_name='skill_name_idx',
        ),
        migrations.AlterField(
            model_name='atsanalysis',
            name='ats_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 100.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='atsanalysis',
            name='missing_keywords',
            field=models.JSONField(default=list, help_text='List of keywords present in JD but missing in resume.'),
        ),
        migrations.AlterField(
            model_name='atsanalysis',
            name='recommendations',
            field=models.JSONField(default=list, help_text='List of actionable recommendation strings.'),
        ),
        migrations.AlterField(
            model_name='atsanalysis',
            name='strengths',
            field=models.JSONField(default=list, help_text='List of ATS strength strings from AI analysis.'),
        ),
        migrations.AlterField(
            model_name='atsanalysis',
            name='weaknesses',
            field=models.JSONField(default=list, help_text='List of ATS weakness strings from AI analysis.'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='NULL = does not expire.', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(help_text="e.g. 'Bachelor of Technology', 'MBA'", max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='4-digit year or NULL if currently studying.', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(help_text='University / college / school name.', max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order (0 = most recent first).'),
        ),
        migrations.AlterField(
            model_name='education',
            name='percentage_or_cgpa',
            field=models.CharField(blank=True, default='', help_text="e.g. '8.5 CGPA' or '85%'. Stored as string to accommodate both.", max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.CharField(blank=True, default='', help_text="e.g. 'Computer Science & Engineering'", max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='4-digit year (e.g. 2019).', null=True),
        ),
        migrations.AlterField(
            model_name='jobmatchanalysis',
            name='job_description',
            field=models.TextField(blank=True, default='', help_text='Raw JD text used for matching. Not shown in public view.'),
        ),
        migrations.AlterField(
            model_name='jobmatchanalysis',
            name='match_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0.00–100.00 compatibility score.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='jobmatchanalysis',
            name='matched_skills',
            field=models.JSONField(default=list, help_text='Skills present in both the resume and JD.'),
        ),
        migrations.AlterField(
            model_name='jobmatchanalysis',
            name='missing_skills',
            field=models.JSONField(default=list, help_text='Skills in JD but not in resume.'),
        ),
        migrations.AlterField(
            model_name='jobmatchanalysis',
            name='recommendations',
            field=models.JSONField(default=list, help_text='Actionable improvement suggestions.'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Stored in MEDIA_ROOT/profile_photos/. Never serve base64 blobs.', null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='portfolioprofile',
            name='about_me',
            field=models.TextField(blank=True, default='', help_text='Extended bio / about me section for portfolio page.'),
        ),
        migrations.AlterField(
            model_name='portfolioprofile',
            name='featured_projects',
            field=models.JSONField(default=list, help_text='List of Project PKs to feature on the portfolio page.'),
        ),
        migrations.AlterField(
            model_name='portfolioprofile',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If True, portfolio page is publicly accessible.'),
        ),
        migrations.AlterField(
            model_name='portfolioprofile',
            name='social_links',
            field=models.JSONField(default=dict, help_text="Dict of platform → URL: {'twitter': '...', 'dribbble': '...'}"),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, default='', help_text="Comma-separated list: 'React, Django, PostgreSQL'.", max_length=500),
        ),
        migrations.AlterField(
            model_name='reference',
            name='contact_details',
            field=models.CharField(blank=True, default='', help_text='Email, phone, or LinkedIn URL.', max_length=500),
        ),
        migrations.AlterField(
            model_name='resume',
            name='ats_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Latest ATS score (0.00–100.00). Denormalized for quick listing.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='career_objective',
            field=models.TextField(blank=True, default='', help_text='Career objective statement (often used for freshers).'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If True, the public /resume/<resume_id>/ page is accessible.'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who owns this resume. NULL for anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profession',
            field=models.CharField(blank=True, default='', help_text="Target job role / profession (e.g. 'Full Stack Developer').", max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='professional_summary',
            field=models.TextField(blank=True, default='', help_text='2–4 sentence professional summary paragraph.'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='public_url',
            field=models.CharField(blank=True, default='', help_text='Fully-qualified public URL (set on create).', max_length=500),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template_name',
            field=models.CharField(blank=True, default='classic', help_text='Frontend template key used to render this resume.', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, default='', help_text="Display title for this resume version (e.g. 'Software Engineer - Google').", max_length=255),
        ),
        migrations.AlterField(
            model_name='resumeview',
            name='visitor_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Hashed/anonymized in production for GDPR compliance.', null=True),
        ),
        migrations.AlterField(
            model_name='resumeview',
            name='visitor_type',
            field=models.CharField(choices=[('direct', 'Direct Visit'), ('recruiter', 'Recruiter'), ('embed', 'Embedded Widget'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional 1–5 proficiency rating. NULL means unrated.', null=True),
        ),
        migrations.AlterField(
            model_name='skillgapanalysis',
            name='current_skills',
            field=models.JSONField(default=list, help_text='Skills the candidate currently has (from resume).'),
        ),
        migrations.AlterField(
            model_name='skillgapanalysis',
            name='learning_path',
            field=models.JSONField(default=list, help_text='Ordered list of learning resources / courses.'),
        ),
        migrations.AlterField(
            model_name='skillgapanalysis',
            name='missing_skills',
            field=models.JSONField(default=list, help_text='Skills required for the target role but absent in resume.'),
        ),
        migrations.AlterField(
            model_name='skillgapanalysis',
            name='suggested_skills',
            field=models.JSONField(default=list, help_text='Additional skills that would strengthen the profile.'),
        ),
        migrations.AlterField(
            model_name='skillgapanalysis',
            name='target_role',
            field=models.CharField(blank=True, default='', help_text='The job role this analysis is targeting.', max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Bullet-point responsibilities and achievements.'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, help_text='NULL = currently working here.', null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='role',
            field=models.CharField(help_text='Job title / role.', max_length=255),
        ),
    ]
