# Generated by Django 5.2.15 on 2026-07-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_resume_owner_created_idx_resume_resu_owner_i_bb2668_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='ats_score',
        ),
        migrations.DeleteModel(
            name='ATSAnalysis',
        ),
    ]
